### PR TITLE
GHA badge needs branch argument

### PR DESCRIPTION
**Pull request by ericphanson**
Otherwise it just shows the status of the latest CI build, whether or not it was merged. I hardcoded `main` here but maybe there's a template?

### CODE REVIEW

**Comment by christopher-dG** [comment]
Hm, GitHub seems to suggest that the default URL actually points to the default branch.

image

**Comment by ericphanson** [comment]
yep, check out https://github.com/beacon-biosignals/KeywordSearch.jl (I just put it in a failing state by closing and reopening a failing PR without merging it)

**Comment by ericphanson** [comment]
Ah wait, the default branch has not had any commits run on it, due to a misconfiguration on my end. That's probably the issue.

**Comment by christopher-dG** [comment]
If it turns out to still need the branch attached, I'll add it to #243 which I'm trying to get merged soon. and has a `{{{BRANCH}}}` template

**Pull request closed without merging**
