### PR TITLE
Don't skip interactive mode tests on MacOS

### PR DESCRIPTION
**Pull request by christopher-dG**
Way back TerminalMenus.jl didn't work in Travis OSX tests, but apparently it's all good now. Also realized that using `@spawn` instead of `@async` is kind of useless.

### CODE REVIEW

**Comment by omus** [comment]
Easier to read diff: https://github.com/invenia/PkgTemplates.jl/pull/35/files?w=1

**Comment by christopher-dG** [comment]
> `?w=1`

Mind: Blown

Let me just fix that conflict really quick

**Comment by christopher-dG** [comment]
Rebased

**Comment by christopher-dG** [comment]
As a result of #31, defining `interactive` on any `Documenter` subtype isn't safe (as demonstrated by the broken tests) so I've moved it to `GitHubPages`.

**Pull request merged**
