### PR TITLE
Allow test failures on Julia nightly

### PR DESCRIPTION
**Pull request by DilumAluthge**
Closes #212

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Looks like this is working correctly.

@christopher-dG 

@SaschaMann

**Comment by SaschaMann** [comment]
I don't like this as a default. It hides the build status of nightly builds completely, so you have to manually check them. I think it's better to have this as an option.

(Personally I don't mind failing checks but set the builds that must pass as required instead)

**Comment by christopher-dG** [comment]
This is only for this repo, not for generated packages. Cassette is a test dependency which often fails on nightly.

**Comment by christopher-dG** [comment]
I wonder why the coverage is so much worse... but oh well.

**Pull request merged**
