### PR TITLE
Add ISC license to the list of options

### PR DESCRIPTION
**Pull request by juliohm**
The option was missing even though the license is supported.

Could you please review and merge?

### CODE REVIEW

**Comment by christopher-dG** [comment]
Oops, my mistake. Can you just change the spelling of "licence" to "license" for consistency?

**Comment by juliohm** [comment]
Done, thanks for catching it.

**Comment by juliohm** [comment]
After you merge, could you please release a new version?

**Comment by christopher-dG** [comment]
Done and done. Thanks! :+1:

**Pull request merged**
