### PR TITLE
integrate OnlinePackage.jl

### PR DESCRIPTION
**Pull request by bramtayl**

### CODE REVIEW

**Comment by bramtayl** [comment]
Closes #46. Also adds a new feature for storing semi-permanent settings (because OnlinePackage needs to store tokens)

**Comment by bramtayl** [comment]
Closes #46. Also adds a new feature for storing semi-permanent settings (because OnlinePackage needs to store tokens)

**Comment by christopher-dG** [comment]
Thanks for this! I will probably put this on top of #61 after it's merged since it changes the plugin API. I should really finish that PR.

**Comment by bramtayl** [comment]
Bump

**Comment by christopher-dG** [comment]
Sorry, I've been away from the computer for the most part. It'll get done eventually :tm:.

**Comment by christopher-dG** [comment]
Closing this because adapting it to #61 would be a lot of work, but I will come back to the branch for reference later on.
Despite it not being merged, thank you for putting in the effort on this @bramtayl! :heart: The feature will surely find its way in soon after PkgTemplates 0.7.

**Pull request closed without merging**
