### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joergbuchwald**
fix function call

### CODE REVIEW

**Comment by christopher-dG** [comment]
It's not incorrect, Template instances are callable

**Comment by joergbuchwald** [comment]
But I get the following error:
ERROR: MethodError: objects of type Template are not callable

**Comment by christopher-dG** [comment]
Use master branch 😊

**Comment by joergbuchwald** [comment]
Ah okay, sorry. However, I think it is a good idea to point to both variants.

**Pull request closed without merging**
