### PR TITLE
Add Online plugin

### PR DESCRIPTION
**Pull request by bramtayl**
Updates #79 to the new infrastructure

### CODE REVIEW

**Comment by nickrobinson251** [comment]
Is this tied to Github? If so I do not think it should have such a generic name as `Online`

**Comment by bramtayl** [comment]
Yes it is. What should I call it?

**Comment by bramtayl** [comment]
Bump

**Comment by christopher-dG** [comment]
Hi, I'll have a look sometime this week or weekend, I've been busy.

**Comment by bramtayl** [comment]
Np. The rewrite looks great!

**Comment by bramtayl** [comment]
Sure, feel free to change it however you want

**Comment by bramtayl** [comment]
So...I think github actions are amazing and basically make this ancient tech. Feel free to reopen if you want.

**Comment by bramtayl** [comment]
Well, I've updated OnlinePackage to work with GitHub actions

**Comment by bramtayl** [comment]
@christopher-dG it looks like documenter doesn't require a separate SSH key anymore, and neither does codecov, but CompatHelper does, so I think this is still useful. Do you want me to try to revive the PR?

**Pull request closed without merging**
